# Automatically generated by pb2py
from __future__ import absolute_import
from .. import protobuf as p


class SkycoinAddress(p.MessageType):
    FIELDS = {
        1: ('seed', p.UnicodeType, 0),
    }
    MESSAGE_WIRE_TYPE = 114
